version: '3.4'

services:
  lazycicadaapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/cert.aspnetcore.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234567   
#    depends_on:
#      - postgres
#    links:
#      - postgres
    ports:
      - "53711:80"
      - "44356:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  postgres:
    image: postgres
    #hostname: postgres
    build:
        context: .
        dockerfile: DockerfilePostgre
    ports:
        - "5432:5432"
    #container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    restart: always

  # pgAdmin client
  pgadmin:
    image: dpage/pgadmin4
    ports:
        - "5555:80"
    links:
      - postgres
    container_name: pgadmin
    environment:
        PGADMIN_DEFAULT_EMAIL: lazycicada@everis.com
        PGADMIN_DEFAULT_PASSWORD: root
    restart: always 
    